name: Deploy to Databricks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Databricks CLI
      run: |
        # Install the latest Databricks CLI using the official installer
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
        # Add to PATH
        echo "$HOME/.databricks/bin" >> $GITHUB_PATH
        # Verify the CLI version and bundle support
        databricks --version
        
    - name: Configure Databricks CLI
      run: |
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databrickscfg
        echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databrickscfg
        
    - name: Deploy to Databricks
      run: |
        databricks bundle deploy --target dev
        
    - name: Run job
      run: |
        databricks bundle run --target dev
