name: Simple Deploy to Databricks

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Databricks CLI
      run: |
        # Install the new Databricks CLI that supports bundles
        pip install databricks-cli[sql,compute,deploy,fs,workspace,iam,secrets,ml,experiments,feature-store,serving,marketplace,vector-search,ai,unity-catalog]
        
    - name: Configure Databricks CLI
      run: |
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databrickscfg
        echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databrickscfg
        
    - name: Deploy to Databricks
      run: |
        databricks bundle deploy --target dev
        
    - name: Run job
      run: |
        databricks bundle run --target dev
